name: env_s3
channels:
  - terradue
  - defaults
  - conda-forge
dependencies:
  - python=3.6.6
  - snap=7.0.0
  - snappy=6.0
  - poppler=0.65.0
  - ipykernel
  - gdal=2.3.2
  - folium
  - instac
  - lxml
  - shapely
  - geopandas
