name: env_burned_area
channels:
  - terradue
  - conda-forge
  - defaults
dependencies:
  - cioppy
  - snap
  - ipykernel
  - otb
  - gdal>2.2.2
  - poppler<0.66
  - geopandas
  - lxml
  - shapely
  - pyyaml
  - imageio
  - parso=0.7
